<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ahmed-Satellite-P755D" name="Default test" tests="13" failures="1" timestamp="10 May 2015 17:33:47 GMT" time="12.425" errors="0">
  <testcase name="SendConversationMessage" time="0.063" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="addToConversation" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="createConversation" time="0.001" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="createMessage" time="12.156" classname="com.FCI.SWE.Services.NotificationServiceTest">
    <failure type="java.lang.AssertionError" message="expected [OK] but found [Failed]">
      <![CDATA[java.lang.AssertionError: expected [OK] but found [Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.FCI.SWE.Services.NotificationServiceTest.createMessage(NotificationServiceTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- createMessage -->
  <testcase name="deleteFriendRequest" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getAllMessages" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getConversationMessages" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getFriendRequestByID" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getMessagesByID" time="0.018" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getUnseenConversationMessages" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getUnseenFriendRequests" time="0.002" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="getUnseenMessages" time="0.001" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
  <testcase name="sendFriendRequest" time="0.001" classname="com.FCI.SWE.Services.NotificationServiceTest"/>
</testsuite> <!-- Default test -->
